### ISSUE TITLE
语言必须设置为“中文”吗?

### ISSUE THREAD

**Issue by imRadwolf** [Madfater/AutoTT#1]
你好，

首先，感谢您的工作！

在您的自述文件中，您指定必须将语言设置为“中文”。如果语言设置为英语，它真的需要还是机器人仍然可以工作？

亲切的问候！

-------------------------

Hello,

First of all, thank you for your work !

In your readme you specify that language has to be set to "chinese". Is it truly required or would the robot still work if the language is set to english ?

Kind regards!

**Comment by imRadwolf** [comment]
我還有一個問題：如果我理解正確，您的 FreeTem 腳本會自動購買“Temcard+”，但捕獲率只能達到 70% 到 80%。

您能否告訴我要自動購買 Temcard++ 需要做什麼？

非常感謝您提前！

------------------------

I have another question : If I understand correctly, your script for FreeTem buys automatically "Temcard+" but these only reach 70% to 80% catch rate.

Could you please tell me what need to be done in order to automatically buy Temcard++ ?

Thank you very much in advance !

**Comment by Madfater** [comment]
@imRadwolf 
If you want to let this project work in english, you need to change the picture in img into english.
Because I use opencv to detect the picture on the screen.

**Comment by Madfater** [comment]
@imRadwolf 
My script for FreeTem buys automatically is made by recording my keyboard and mouse. Therefore, every step is fixed.
If you need the temcard++ version, I will add in the future version

**Comment by Madfater** [comment]
@imRadwolf 
And, the current version in the release has a lot of bugs.
You can wait for me to update or use the code.

Sorry for my poor English

**Comment by imRadwolf** [comment]
Your english is very good ! Don't worry about it :)

I love the way you are coding your project and I will be happy to help :
- With the translation (English/french)
- Small features like the Temcard++ (I've already managed to find where the implement it !

It is true that this release has a lot of bugs but I'm excited to see what's next !
I'll be on the lookout to use your project and, If I can, help improve it!

You can close this issue ^^
